import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react"; 
import Navbar from "@/app/components/NavBar/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
      <body className={inter.className}>    
      <NextUIProvider>
        <div className="bg-black  h-max">
        <Navbar />
          {children}
          </div>
      </NextUIProvider>
      </body>
    </html>
  );
}
